version: 2.1

executors:
  default_executor:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m

jobs:
  build:
    executor: default_executor
    steps:
      - checkout
      - restore_cache:
          key: aviationdata-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies --no-daemon
      - save_cache:
          paths:
            - ~/.gradle
          key: aviationdata-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run:
          name: Assemble Debug APK
          command: ./gradlew clean assembleDebug -xlint -PdisablePreDex --no-daemon
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk

  check:
    executor: default_executor
    steps:
      - run:
          name: Check code style
          command: ./gradlew clean ktlintCheck --no-daemon
      - run:
          name: Run Detekt
          command: ./gradlew clean detekt --no-daemon

  test:
    executor: default_executor
    steps:
      - run:
          name: Generate all unit test reports
          command: ./gradlew clean jacocoTestReportDebug --no-daemon
      - run:
          name: Upload reports to Codecov
          command: bash <(curl -s https://codecov.io/bash -v)
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

workflows:
  version: 2
  build_check_tests_deploy:
    jobs:
      - build
      - check:
          requires:
            - build
      - test:
          requires:
            - build